version: '3.8'
services:
  postgres-dev:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_DB=dev
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  postgres-test:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_DB=test
    volumes:
      - postgres-test:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres-dev:
  postgres-test: